CDEBUG = -g -Wall

PROG = CGLShader

CPP_SRC = \
CGLShaderInit.cpp \
CGLTexture.cpp \

EXTRA_CFLAGS = \
-I../../include/CGLShader \
-I$(INC_DIR)/CImageLib \
-I$(INC_DIR)/CFileType \
-I$(INC_DIR)/CFile \
-I$(INC_DIR)/CUtil \
-I$(INC_DIR)/CStrUtil \
-I$(INC_DIR)/CMath \

include $(MAKE_DIR)/lib.mk
